name: On TileBoard Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Newly released TileBoard version
        required: true
      release_url:
        description: The URL of the TileBoard release
        required: true

jobs:
  build-addon:
    name: Bump TileBoard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # with tags

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: yarn install

      - name: Update version
        run: |
          git config --local user.email "autorelease-invalid@email.com"
          git config --local user.name "Autorelease"
          jq  '.args.TILEBOARD_VERSION = "${{ github.event.inputs.version }}"' addon/build.json > addon/build_new.json
          mv addon/build_new.json addon/build.json
          git add ./addon/build.json
          git commit -m 'chore(bump): TileBoard ${{ github.event.inputs.release_url }}'
          git push --follow-tags
